language: java
jdk: oraclejdk8
services:
  - mysql
test:
  database: budgtDevelopment
  username: travis
  encoding: utf8
before_install:
  - mysql -e 'CREATE DATABASE budgtDevelopment; update user set authentication_string=PASSWORD('password') where User='travis'; FLUSH PRIVILEGES;'